-- ====================================================================
-- Schema: BankKonten CMS Database
-- Author: Gemini
-- Description: Skema database PostgreSQL untuk Supabase, dirancang untuk
--              mengelola konten website BankKonten melalui CMS.
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. EXTENSIONS & HELPER FUNCTIONS
-- --------------------------------------------------------------------

-- Pastikan ekstensi untuk gen_random_uuid tersedia
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Fungsi untuk auto-update kolom `updated_at`
CREATE OR REPLACE FUNCTION public.handle_updated_at() 
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- --------------------------------------------------------------------
-- 2. TABLE CREATION
-- --------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.hero_section (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  subtitle TEXT,
  button_text TEXT,
  button_link TEXT,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `hero_section`
DROP TRIGGER IF EXISTS on_hero_section_updated ON public.hero_section;
CREATE TRIGGER on_hero_section_updated
  BEFORE UPDATE ON public.hero_section
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: keunggulan (Multiple Rows)
CREATE TABLE IF NOT EXISTS public.keunggulan (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  icon VARCHAR(50), -- Nama ikon dari library (e.g., 'Shield', 'Zap')
  order_number INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `keunggulan`
DROP TRIGGER IF EXISTS on_keunggulan_updated ON public.keunggulan;
CREATE TRIGGER on_keunggulan_updated
  BEFORE UPDATE ON public.keunggulan
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: why_content (Multiple Rows)
CREATE TABLE IF NOT EXISTS public.why_content (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  order_number INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `why_content`
DROP TRIGGER IF EXISTS on_why_content_updated ON public.why_content;
CREATE TRIGGER on_why_content_updated
  BEFORE UPDATE ON public.why_content
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: pricing_packages (Multiple Rows)
CREATE TABLE IF NOT EXISTS public.pricing_packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  package_name TEXT NOT NULL,
  price VARCHAR(100),
  description TEXT,
  features JSONB, -- Menyimpan fitur sebagai array of strings
  button_text TEXT,
  is_popular BOOLEAN DEFAULT FALSE NOT NULL,
  order_number INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `pricing_packages`
DROP TRIGGER IF EXISTS on_pricing_packages_updated ON public.pricing_packages;
CREATE TRIGGER on_pricing_packages_updated
  BEFORE UPDATE ON public.pricing_packages
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: testimonials (Multiple Rows)
CREATE TABLE IF NOT EXISTS public.testimonials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  role TEXT,
  message TEXT NOT NULL,
  photo_url TEXT,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `testimonials`
DROP TRIGGER IF EXISTS on_testimonials_updated ON public.testimonials;
CREATE TRIGGER on_testimonials_updated
  BEFORE UPDATE ON public.testimonials
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: urgency_section (Single Row)
CREATE TABLE IF NOT EXISTS public.urgency_section (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  button_text TEXT,
  button_link TEXT,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `urgency_section`
DROP TRIGGER IF EXISTS on_urgency_section_updated ON public.urgency_section;
CREATE TRIGGER on_urgency_section_updated
  BEFORE UPDATE ON public.urgency_section
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: navbar_links (Multiple Rows)
CREATE TABLE IF NOT EXISTS public.navbar_links (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  label TEXT NOT NULL,
  href TEXT NOT NULL,
  order_number INT DEFAULT 0,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `navbar_links`
DROP TRIGGER IF EXISTS on_navbar_links_updated ON public.navbar_links;
CREATE TRIGGER on_navbar_links_updated
  BEFORE UPDATE ON public.navbar_links
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: footer_content (Single Row)
CREATE TABLE IF NOT EXISTS public.footer_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  brand_name TEXT,
  description TEXT,
  phone VARCHAR(20),
  email VARCHAR(255),
  address TEXT,
  copyright_text TEXT,
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `footer_content`
DROP TRIGGER IF EXISTS on_footer_content_updated ON public.footer_content;
CREATE TRIGGER on_footer_content_updated
  BEFORE UPDATE ON public.footer_content
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- Tabel: whatsapp_settings (Single Row)
CREATE TABLE IF NOT EXISTS public.whatsapp_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  phone_number VARCHAR(20) NOT NULL,
  message TEXT, -- Pre-filled message
  is_active BOOLEAN DEFAULT TRUE NOT NULL,
  metadata JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Trigger untuk `whatsapp_settings`
DROP TRIGGER IF EXISTS on_whatsapp_settings_updated ON public.whatsapp_settings;
CREATE TRIGGER on_whatsapp_settings_updated
  BEFORE UPDATE ON public.whatsapp_settings
  FOR EACH ROW
  EXECUTE PROCEDURE public.handle_updated_at();

-- --------------------------------------------------------------------
-- 3. ROW LEVEL SECURITY (RLS)
-- --------------------------------------------------------------------

-- Enable RLS for all tables
ALTER TABLE public.hero_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.keunggulan ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.why_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pricing_packages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.urgency_section ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.navbar_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.footer_content ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.whatsapp_settings ENABLE ROW LEVEL SECURITY;

-- Policies for public read access (for Landing Page)
DROP POLICY IF EXISTS "Public can read all hero_section" ON public.hero_section;
DROP POLICY IF EXISTS "Public can read all keunggulan" ON public.keunggulan;
DROP POLICY IF EXISTS "Public can read all why_content" ON public.why_content;
DROP POLICY IF EXISTS "Public can read all pricing_packages" ON public.pricing_packages;
DROP POLICY IF EXISTS "Public can read all testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Public can read all urgency_section" ON public.urgency_section;
DROP POLICY IF EXISTS "Public can read all navbar_links" ON public.navbar_links;
DROP POLICY IF EXISTS "Public can read all footer_content" ON public.footer_content;
DROP POLICY IF EXISTS "Public can read all whatsapp_settings" ON public.whatsapp_settings;
CREATE POLICY "Public can read all hero_section" ON public.hero_section FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all keunggulan" ON public.keunggulan FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all why_content" ON public.why_content FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all pricing_packages" ON public.pricing_packages FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all testimonials" ON public.testimonials FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all urgency_section" ON public.urgency_section FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all navbar_links" ON public.navbar_links FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all footer_content" ON public.footer_content FOR SELECT TO public USING (is_active = true);
CREATE POLICY "Public can read all whatsapp_settings" ON public.whatsapp_settings FOR SELECT TO public USING (is_active = true);

-- Policies for admin full access (for Admin Panel)
-- Batasi write hanya untuk user yang terdaftar di public.admin_users dengan role admin/super_admin
-- Drop policies lama bila ada
DROP POLICY IF EXISTS "Admins have full access to hero_section" ON public.hero_section;
DROP POLICY IF EXISTS "Admins have full access to keunggulan" ON public.keunggulan;
DROP POLICY IF EXISTS "Admins have full access to why_content" ON public.why_content;
DROP POLICY IF EXISTS "Admins have full access to pricing_packages" ON public.pricing_packages;
DROP POLICY IF EXISTS "Admins have full access to testimonials" ON public.testimonials;
DROP POLICY IF EXISTS "Admins have full access to urgency_section" ON public.urgency_section;
DROP POLICY IF EXISTS "Admins have full access to navbar_links" ON public.navbar_links;
DROP POLICY IF EXISTS "Admins have full access to footer_content" ON public.footer_content;
DROP POLICY IF EXISTS "Admins have full access to whatsapp_settings" ON public.whatsapp_settings;

-- Buat policies baru yang memverifikasi role admin
DROP POLICY IF EXISTS "Admin users can manage hero_section" ON public.hero_section;
CREATE POLICY "Admin users can manage hero_section"
ON public.hero_section
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage keunggulan" ON public.keunggulan;
CREATE POLICY "Admin users can manage keunggulan"
ON public.keunggulan
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage why_content" ON public.why_content;
CREATE POLICY "Admin users can manage why_content"
ON public.why_content
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage pricing_packages" ON public.pricing_packages;
CREATE POLICY "Admin users can manage pricing_packages"
ON public.pricing_packages
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage testimonials" ON public.testimonials;
CREATE POLICY "Admin users can manage testimonials"
ON public.testimonials
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage urgency_section" ON public.urgency_section;
CREATE POLICY "Admin users can manage urgency_section"
ON public.urgency_section
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage navbar_links" ON public.navbar_links;
CREATE POLICY "Admin users can manage navbar_links"
ON public.navbar_links
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage footer_content" ON public.footer_content;
CREATE POLICY "Admin users can manage footer_content"
ON public.footer_content
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

DROP POLICY IF EXISTS "Admin users can manage whatsapp_settings" ON public.whatsapp_settings;
CREATE POLICY "Admin users can manage whatsapp_settings"
ON public.whatsapp_settings
FOR ALL
TO authenticated
USING (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')))
WITH CHECK (EXISTS (SELECT 1 FROM public.admin_users au WHERE au.user_id = auth.uid() AND au.role IN ('admin','super_admin')));

-- ====================================================================
-- End of Schema
-- ====================================================================
